### ISSUE TITLE
Helper "Book" icons gone

### ISSUE THREAD

**Issue by MythicalRollers** [mclemente/compendium-browser#10]
Foundry: 11.315
dnd5e: 3.0.3
CB: 2.2.3
The helper Book icons on Character Sheet are gone.  I have tried with default "New" character sheet, Legacy Sheet, and Updated Tidy5e Sheet.  I have disabled all modules except CB to test "New" Character and Legacy sheets.  Then only turned on Tidy5e sheet to test that before turning all my modules on.  I posted error logs in my submission about the new "Features" tab, which may or may not be related.

**Comment by mclemente** [comment]
Were you using the Legacy sheet before? I forgot it was still available so I removed the whole thing assuming it was broken/unnecessary. I'll get it back on the next release.

**Comment by MythicalRollers** [comment]
We used it for the dope book icon.  Mainly use Tidy5e sheet now that its 3.0+ version is pretty stable.  If it's gone that's fine.  I had just made a "How To" video for my players on using the module. I can just make a new one lol.

**Comment by mclemente** [comment]
Then I'll be closing this as a wontfix. Thank your for understanding.
