### ISSUE TITLE
Spell filter with class not working - translation error?

### ISSUE THREAD

**Issue by Gridomin** [mclemente/compendium-browser#17]
Hi,
I love your mod, but it seems, that it is not working correctly for me:
i am trying so "filter" spells for a specific class, for example cleric. But I get only 2 spells shown.
![Screenshot 2024-07-09 200914](https://github.com/mclemente/compendium-browser/assets/101142520/fa4d1afa-3b3e-4b21-98c3-47c994295dd7)

The original srd-compendiums are untouched, but I am using the german translation of dnd5e with babele.
Thank you!

**Comment by Tmnath** [comment]
I'm having the same issue, the only spells that appear in the filter are the untranslated ones.
