### ISSUE TITLE
Filter not found when opening browser from Spellbook tab of spellcasters

### ISSUE THREAD

**Issue by flyingsquad** [mclemente/compendium-browser#3]
I'm getting the following error with Foundry 11.315 and DnD5e 2.3.1, generated at line 1614 in compendium-browser.js, when I click the browser button on spellcasting characters from the Spellbook tab of the character sheet:

filter not found: tab:spell CMPBrowsergeneral, ITEM.TypeClass.

I don't get the error when opening the browser from the Spellbook on characters that don't cast spells, nor do I get it when I open the browser directly. 

The error also occurs on a separate installation of DnD5e 2.4.0.

Looking at the source code I see a call to addSpellFilter that looks like it adds this filter (line 1991), so it appears that there's something missing from the character that the filter is using to trigger the filter. I'm suspecting ITEM.TypeClass is expected to be on the actor to tell it what class to search for? 

Above that is a comment:
    // JV-082: Fix for missing "Class" search feature

Thanks for any assistance you can give. This would be extremely handy to have available for my players. It would be so much easier to explain to them than the manual process of opening the browser and selecting the class.

**Comment by ZoltanTheDM** [comment]
Fix is in https://github.com/mclemente/compendium-browser/pull/2
You can install it manually from `https://github.com/ZoltanTheDM/compendium-browser-2/releases/download/v2.1.0-beta4/module.json` Also adds a few more buttons on the Race, Class, and Background sections that do similar things.

**Comment by mclemente** [comment]
I just accepted the PR, so it should be fixed now.
