### ISSUE TITLE
Spells cannot be found on DnD 2.4.1

### ISSUE THREAD

**Issue by DreamingHero1997** [mclemente/compendium-browser#5]
The compendium was infinitely searching for spells when using DnD 2.4.1, I only had compendium browser enabled to test this.
Updating to 3.0 and the spells started showing up again.

**Comment by mclemente** [comment]
I can't support two system versions. Revert back to Compendium Browser v2.1. Manifest: `https://github.com/mclemente/compendium-browser/releases/download/2.1.0/module.json`
