### ISSUE TITLE
New "Features" Tab not loading.

### ISSUE THREAD

**Issue by MythicalRollers** [mclemente/compendium-browser#9]
Updated to 2.2.3 after being released.
Open CB from Compendium tab Spells and Items work just fine.  Features does not.  Copy and pasted error below.  I have also turned off all modules except for CB and my Compendium
Foundry: 11..315
dnd5e: 3.0.3
cb: 2.2.3

![image](https://github.com/mclemente/compendium-browser/assets/106455111/033c9bd1-8f1e-42aa-8271-6748c914b0d4)

compendium-browser.js:1324 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'label')
    at compendium-browser.js:1324:23
    at Array.map (<anonymous>)
    at CompendiumBrowser._sortPackValues (compendium-browser.js:1322:5)
    at CompendiumBrowser.addSpellFilters (compendium-browser.js:1156:9)
    at CompendiumBrowser.ready (compendium-browser.js:36:8)
    at async Object.fn (compendium-browser.js:1558:2)
(anonymous) @ compendium-browser.js:1324
_sortPackValues @ compendium-browser.js:1322
addSpellFilters @ compendium-browser.js:1156
ready @ compendium-browser.js:36
await in ready (async)
(anonymous) @ compendium-browser.js:1558
#call @ foundry.js:730
callAll @ foundry.js:687
setupGame @ foundry.js:8746
await in setupGame (async)
_initializeGameView @ foundry.js:9990
_initializeView @ foundry.js:9966
initialize @ foundry.js:8650
compendium-browser.js:1324 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'label')
    at compendium-browser.js:1324:23
    at Array.map (<anonymous>)
    at CompendiumBrowser._sortPackValues (compendium-browser.js:1322:5)
    at CompendiumBrowser.addFeatFilters (compendium-browser.js:1262:9)
    at CompendiumBrowser.ready (compendium-browser.js:37:8)
    at async Object.fn (compendium-browser.js:1558:2)
(anonymous) @ compendium-browser.js:1324
_sortPackValues @ compendium-browser.js:1322
addFeatFilters @ compendium-browser.js:1262
ready @ compendium-browser.js:37
await in ready (async)
(anonymous) @ compendium-browser.js:1558
#call @ foundry.js:730
callAll @ foundry.js:687
setupGame @ foundry.js:8746
await in setupGame (async)
_initializeGameView @ foundry.js:9990
_initializeView @ foundry.js:9966
initialize @ foundry.js:8650
compendium-browser.js:890 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'includes')
    at CompendiumBrowser.decorateItem (compendium-browser.js:890:43)
    at CompendiumBrowser.<anonymous> (compendium-browser.js:471:37)
    at Array.reduce (<anonymous>)
    at compendium-browser.js:458:16
    at async CompendiumBrowser.loadAndFilterItems (compendium-browser.js:419:6)
    at async CompendiumBrowser.renderItemData (compendium-browser.js:761:16)
    at async CompendiumBrowser.replaceList (compendium-browser.js:726:26)

**Comment by mclemente** [comment]
Do you have any custom classes? What are they named?

**Comment by MythicalRollers** [comment]
Nope, no custom classes. Just the "official" ones from dndbeyond.  No homebrews.
![image](https://github.com/mclemente/compendium-browser/assets/106455111/cd34f711-4690-47de-8f7b-c0e464ef79b7)

**Comment by mclemente** [comment]
Do they lack an identifier?

**Comment by MythicalRollers** [comment]
They do have identifiers.  I just checked.  They did show up in the previous version with the only on not being blood hunter.

**Comment by mclemente** [comment]
That is weird. It is failing when reading their data, and it is the exact same logic that the Spells tab's filter uses, so both should be throwing errors intead.

**Comment by mclemente** [comment]
I've added a new error message that should tell which class is throwing the error, so that should make it easier to solve this.

**Comment by MythicalRollers** [comment]
Okay, after about an hour of messing around.  I figured out that CB wants to see "blood-hunter" as an identifier and not "bloodhunter".  Which is fine, but weird that is preset somewhere.  How will CB handle custom Classes?
The other rub, the "label" error is gone and is replaced by:

compendium-browser.js:1325 Compendium Browser | Pack Value "" has no data.
(anonymous) @ compendium-browser.js:1325
_sortPackValues @ compendium-browser.js:1322
addFeatFilters @ compendium-browser.js:1262
ready @ compendium-browser.js:37
await in ready (async)
(anonymous) @ compendium-browser.js:1562
#call @ foundry.js:730
callAll @ foundry.js:687
setupGame @ foundry.js:8746
await in setupGame (async)
_initializeGameView @ foundry.js:9990
_initializeView @ foundry.js:9966
initialize @ foundry.js:8650

This seems to be true no matter if I have only 1 compendium being allowed such as Spells or not.

However as soon as I enable the Class Features Compendium, that is when the "includes" error populates.

compendium-browser.js:890 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'includes')
    at CompendiumBrowser.decorateItem (compendium-browser.js:890:43)
    at CompendiumBrowser.<anonymous> (compendium-browser.js:471:37)
    at Array.reduce (<anonymous>)
    at compendium-browser.js:458:16
    at async CompendiumBrowser.loadAndFilterItems (compendium-browser.js:419:6)
    at async CompendiumBrowser.renderItemData (compendium-browser.js:761:16)
    at async CompendiumBrowser.replaceList (compendium-browser.js:726:26)

Is CB looking for Class Features to be tied back to a class somewhere?

**Comment by mclemente** [comment]
> I figured out that CB wants to see "blood-hunter" as an identifier and not "bloodhunter". Which is fine, but weird that is preset somewhere. How will CB handle custom Classes?

CB doesn't care how it is written. All that matters is:

- Class has an identifier.
- Subclass has that identifier set to its Class Identifier.
- Feature has the name of class/subclass set on its Requirements.

**Comment by MythicalRollers** [comment]
Even if I point CB to look at SRD content.  As soon as I check "Class Features" it throws up the "includes" error. 

![image](https://github.com/mclemente/compendium-browser/assets/106455111/e492f50e-edcc-45ca-9a30-841b263c8c88)
![image](https://github.com/mclemente/compendium-browser/assets/106455111/66672dd1-5f12-47bb-bc7d-a1f3f7fe0cac)

Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'includes')
    at CompendiumBrowser.decorateItem (compendium-browser.js:890:43)
    at CompendiumBrowser.<anonymous> (compendium-browser.js:471:37)
    at Array.reduce (<anonymous>)
    at compendium-browser.js:458:16
    at async CompendiumBrowser.loadAndFilterItems (compendium-browser.js:419:6)
    at async CompendiumBrowser.renderItemData (compendium-browser.js:761:16)
    at async CompendiumBrowser.replaceList (compendium-browser.js:726:26)

**Comment by mclemente** [comment]
I was about to make a new release with a tentative fix after sending the message. I wasn't expecting you'd reply so fast lol

That "includes" error is some subclass having a class identifier for a class that isn't present (or that has a different class identifier), so it creates the class entry without a label.

I've added a filter on the next release so that error shouldn't happen anymore.

**Comment by MythicalRollers** [comment]
Whatever magic you just did, I no longer get that error and my stuff loads.

**Comment by MythicalRollers** [comment]
Homie fixed this in Feb.
